version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2

    steps:
      # Start JSON Server container in the background
      - run:
          name: Start JSON Server
          background: true
          command: |
            docker run -d \
              -p 3000:3000 -v `pwd`:/data \
              --name json-server \
              williamyeh/json-server \
              --watch db.json

      # Wait for JSON Server to be ready
      - run:
          name: Wait for JSON Server to start
          command: |
            until curl --output /dev/null --silent --head --fail http://localhost:3000; do
              sleep 1
            done

  front-end:
    docker:
      - image: cimg/node:20.1.0
    steps:
      - checkout
      # Run curl command to connect to JSON Server
      - run:
          name: Wait for JSON Server to start
          command: |
            until curl --output /dev/null --silent --head --fail http://localhost:3000; do
              sleep 1
            done
      - run:
          name: Connect to JSON Server
          command: |
            curl http://localhost:3000/posts/1

workflows:
  test_and_distribute:
    jobs:
      - build
      - front-end


